collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7199217
  brandStrength: 0.480666
  lightness: 0.3424746
  brandColors:
    - '#000000'
    - '#BD1F21'
    - '#FFFFFF'
    - '#706764'
    - '#D0C7C2'
  rhythmicContrast: 0.7173916
typography_spectrum: 0.6666237
layout_spectrum: 0
name: Loco Steaks
